Promise.reject(10)
.then(x => console.log(x))
.catch(err => console.log(err));
